version: 0.2

phases:
  build:
    commands:
    - echo "This is build phase... Zipping my lambda function"
    - zip -r deployment_package.zip .*/
  post_build:
    commands:
    - echo "Deploying to the Lambd"
    - aws lambda update-function-code --function-name  Hello_world --zip-file fileb://deployment_package.zip
artifacts:
  type: zip
  paths:
    - '*'
