version: 0.2

phases:
  build:
    commands:
      # Build your Lambda code here
      - zip -r my-lambda-package.zip .*/

  post_build:
    commands:
      - aws s3 cp my-lambda-package.zip s3://artifactsdatastore/
      - aws lambda update-function-code --function-name hello_world --s3-bucket artifactsdatastore --s3-key my-lambda-package.zip
